const fs = require("fs");
const lines = [];
lines.push("package com.civicos.platform.domain.incident.domain;");
lines.push("");
lines.push("import org.springframework.data.jpa.repository.JpaRepository;");
lines.push("import org.springframework.data.jpa.repository.Query;");
lines.push("import org.springframework.data.repository.query.Param;");
lines.push("import org.springframework.stereotype.Repository;");
lines.push("");
lines.push("import java.util.List;");
lines.push("import java.util.Optional;");
lines.push("");
lines.push("@Repository");
lines.push("public interface IncidentCategoryRepository");
lines.push("        extends JpaRepository<IncidentCategory, Long> {");
lines.push("");
lines.push("    Optional<IncidentCategory> findByCode(String code);");
lines.push("");
lines.push("    @Query(value = """SELECT DISTINCT ON (ic.id)");
lines.push("    ic.id, ic.name, ic.code, ic.description, ic.keywords, ic.citizen_actions, ic.created_at, ic.updated_at,");
lines.push("    COALESCE(d_specific.id, d_default.id) as dept_id,");
lines.push("    COALESCE(d_specific.code, d_default.code) as dept_code,");
lines.push("    COALESCE(d_specific.name, d_default.name) as dept_name,");
lines.push("    COALESCE(d_specific.jurisdiction_level, d_default.jurisdiction_level) as dept_jurisdiction,");
lines.push("    COALESCE(d_specific.complaint_portal_url, d_default.complaint_portal_url) as dept_complaint_url,");
lines.push("    COALESCE(d_specific.website_url, d_default.website_url) as dept_website_url");
lines.push("FROM incident_categories ic");
lines.push("JOIN departments d_default ON ic.department_id = d_default.id");
lines.push("LEFT JOIN incident_category_departments icd ON ic.id = icd.incident_category_id");
lines.push("LEFT JOIN departments d_specific ON icd.department_id = d_specific.id");
lines.push("    AND ((d_specific.jurisdiction_level = 'STATE' AND d_specific.jurisdiction_value = :stateCode)");
lines.push("        OR (d_specific.jurisdiction_level = 'DISTRICT' AND d_specific.jurisdiction_value = :districtCode))");
lines.push("WHERE ic.keywords && CAST(:keywords AS text[])");
lines.push("ORDER BY ic.id,");
lines.push("    CASE WHEN d_specific.jurisdiction_level = 'DISTRICT' THEN 1");
lines.push("        WHEN d_specific.jurisdiction_level = 'STATE' THEN 2 ELSE 3 END""", nativeQuery = true)");
lines.push("    List<Object[]> searchByKeywordsAndLocation(@Param("keywords") String[] keywords,");
lines.push("            @Param("stateCode") String stateCode, @Param("districtCode") String districtCode);");
lines.push("");
lines.push("    @Query(value = """SELECT ic.*, 1 - (ic.embedding <=> CAST(:embedding AS vector)) AS similarity");
lines.push("FROM incident_categories ic");
lines.push("INNER JOIN incident_category_departments icd ON icd.incident_category_id = ic.id");
lines.push("INNER JOIN departments d ON d.id = icd.department_id");
lines.push("WHERE ic.embedding IS NOT NULL");
lines.push("AND 1 - (ic.embedding <=> CAST(:embedding AS vector)) > :threshold");
lines.push("AND (:stateCode IS NULL OR d.state_code = :stateCode OR d.jurisdiction_level = 'CENTRAL')");
lines.push("ORDER BY ic.embedding <=> CAST(:embedding AS vector) LIMIT 3""", nativeQuery = true)");
lines.push("    List<Object[]> searchByEmbedding(@Param("embedding") String embedding,");
lines.push("            @Param("stateCode") String stateCode, @Param("threshold") double threshold);");
lines.push("}");
fs.writeFileSync("src/main/java/com/civicos/platform/domain/incident/domain/IncidentCategoryRepository.java", lines.join("\n"));
console.log("OK");
