spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092
    autoconfigure:
      exclude:
        - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

logging:
  level:
    com.civicos: DEBUG
    org.hibernate.SQL: DEBUG